import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F4F7F5",
  },
  content: {
    padding: 20,
    paddingTop: 66,
    paddingBottom: 42,
    gap: 14,
  },
  hero: { gap: 7, marginBottom: 10 },
  eyebrow: {
    color: "#327A68",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  title: {
    color: "#142B27",
    fontSize: 36,
    fontWeight: "800",
    lineHeight: 39,
    letterSpacing: -1.1,
  },
  sub: {
    color: "#66746F",
    fontSize: 15,
    lineHeight: 21,
    maxWidth: 315,
  },
  status: {
    backgroundColor: "#173F36",
    borderRadius: 18,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  dot: { width: 10, height: 10, borderRadius: 5 },
  good: { backgroundColor: "#78E3B4" },
  muted: { backgroundColor: "#AAB7B2" },
  statusLabel: {
    color: "#A9C7BC",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },
  statusValue: {
    color: "#FFF",
    fontSize: 17,
    fontWeight: "700",
    marginTop: 3,
    maxWidth: 190,
  },
  rssi: {
    color: "#78E3B4",
    fontSize: 15,
    fontWeight: "800",
    marginLeft: "auto",
  },
  notice: { backgroundColor: "#FFF0D5", borderRadius: 13, padding: 14, gap: 5 },
  noticeText: { color: "#7A4D00", fontSize: 13, lineHeight: 18, fontWeight: "600" },
  dismiss: { color: "#9B6500", fontSize: 10, fontWeight: "800", letterSpacing: 0.8 },
  label: { color: "#73817C", fontSize: 11, fontWeight: "800", letterSpacing: 1.1, marginTop: 8 },
  floorRow: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  floor: { flexGrow: 1, flexBasis: "30%", minWidth: 96, borderWidth: 1.5, borderColor: "#D2DDD8", padding: 15, borderRadius: 14, gap: 3 },
  activityActive: { backgroundColor: "#1E3A34", borderColor: "#1E3A34" },
  activityTextActive: { color: "#E7F6EF" },
  floorActive: { backgroundColor: "#D8F0E4", borderColor: "#327A68" },
  floorText: { color: "#3A4C46", fontWeight: "800", fontSize: 15 },
  floorSub: { color: "#74827D", fontSize: 11 },
  floorTextActive: { color: "#19614E" },
  metrics: { flexDirection: "row", backgroundColor: "#FFF", paddingVertical: 16, borderRadius: 16 },
  metric: { flex: 1, alignItems: "center", gap: 5, borderRightWidth: 1, borderRightColor: "#E7ECE9" },
  metricLabel: { color: "#84908C", fontSize: 9, fontWeight: "800", letterSpacing: 0.6 },
  metricValue: { color: "#1E322D", fontSize: 14, fontWeight: "800" },
  accent: { color: "#16835F" },
  primary: { padding: 18, borderRadius: 14, alignItems: "center", backgroundColor: "#247C66" },
  stop: { backgroundColor: "#C95748" },
  primaryText: { color: "#FFF", fontWeight: "800", fontSize: 14, letterSpacing: 0.7 },
  secondary: { padding: 14, borderRadius: 12, alignItems: "center", borderWidth: 1.5, borderColor: "#247C66" },
  secondaryText: { color: "#19614E", fontWeight: "800", fontSize: 12 },
  section: { color: "#52635D", fontSize: 11, fontWeight: "800", letterSpacing: 1, marginTop: 11 },
  card: { backgroundColor: "#FFF", borderRadius: 16, paddingHorizontal: 16 },
  row: { paddingVertical: 13, flexDirection: "row", justifyContent: "space-between", gap: 15, borderBottomWidth: 1, borderBottomColor: "#EDF0EE" },
  rowLabel: { color: "#75827D", fontSize: 13 },
  rowValue: { color: "#20352F", fontSize: 13, fontWeight: "700", textAlign: "right", flexShrink: 1 },
  empty: { paddingVertical: 16, color: "#75827D", fontSize: 13 },
  capTitle: { color: "#1D3E35", fontWeight: "800", fontSize: 13, marginTop: 15 },
  cap: { color: "#697973", fontSize: 12, lineHeight: 17, marginTop: 4, marginBottom: 2 },
  actions: { flexDirection: "row", gap: 10, marginTop: 8 },
  action: { flex: 1, borderWidth: 1.5, borderColor: "#AEBEB7", padding: 14, alignItems: "center", borderRadius: 12 },
  actionText: { color: "#31584C", fontWeight: "800", fontSize: 12 },
  disabled: { opacity: 0.42 },
  json: { color: "#327A68", textDecorationLine: "underline", fontWeight: "700", fontSize: 13, textAlign: "center", padding: 5 },
  disabledText: { color: "#9BA8A3" },
  footnote: { color: "#7A8882", fontSize: 11, lineHeight: 16, textAlign: "center", marginTop: 10 },
});
